// -------------------------------------------------------------
// 
// File Name: C:\Users\jwbie\OneDrive\Documents\Academics\F22\551\551_Final_Project\fft_v2\hdl\joe_fft\downsample_top.v
// Created: 2022-12-08 20:30:07
// 
// Generated by MATLAB 9.13 and HDL Coder 4.0
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: downsample_top
// Source Path: joe_fft/downsample_top
// Hierarchy Level: 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module downsample_top
          (clk,
           reset,
           enb,
           data_adc,
           valid_adc,
           rst,
           adc_downsample,
           adc_valid);


  input   clk;
  input   reset;
  input   enb;
  input   [15:0] data_adc;  // uint16
  input   valid_adc;
  input   rst;
  output  [15:0] adc_downsample;  // uint16
  output  adc_valid;


  wire [15:0] downsample_out1;  // uint16
  wire downsample_out2;


  // StartHere
  Downsampler u_downsample_inst (.clk(clk),
                                 .reset(reset),
                                 .enb(enb),
                                 .dataIn(data_adc),  // uint16
                                 .validIn(valid_adc),
                                 .syncReset(rst),
                                 .dataOut(downsample_out1),  // uint16
                                 .validOut(downsample_out2)
                                 );

  assign adc_downsample = downsample_out1;

  assign adc_valid = downsample_out2;

endmodule  // downsample_top

