// -------------------------------------------------------------
// 
// File Name: C:\Users\jwbie\OneDrive\Documents\Academics\F22\551\551_Final_Project\fft_v2\hdl\joe_fft\RADIX22FFT_SDNF2_4_block1.v
// Created: 2022-12-08 20:30:07
// 
// Generated by MATLAB 9.13 and HDL Coder 4.0
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: RADIX22FFT_SDNF2_4_block1
// Source Path: joe_fft/FFT/RADIX22FFT_SDNF2_4
// Hierarchy Level: 2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module RADIX22FFT_SDNF2_4_block1
          (clk,
           reset,
           enb_1_8_0,
           rotate_5,
           dout_5_re,
           dout_5_im,
           dout_7_re,
           dout_7_im,
           dout_1_vld,
           dout_5_re_1,
           dout_5_im_1,
           dout_6_re,
           dout_6_im);


  input   clk;
  input   reset;
  input   enb_1_8_0;
  input   rotate_5;  // ufix1
  input   signed [19:0] dout_5_re;  // sfix20
  input   signed [19:0] dout_5_im;  // sfix20
  input   signed [19:0] dout_7_re;  // sfix20
  input   signed [19:0] dout_7_im;  // sfix20
  input   dout_1_vld;
  output  signed [20:0] dout_5_re_1;  // sfix21
  output  signed [20:0] dout_5_im_1;  // sfix21
  output  signed [20:0] dout_6_re;  // sfix21
  output  signed [20:0] dout_6_im;  // sfix21


  wire signed [20:0] din1_re;  // sfix21
  wire signed [20:0] din1_im;  // sfix21
  wire signed [20:0] din2_re;  // sfix21
  wire signed [20:0] din2_im;  // sfix21
  reg  Radix22ButterflyG2_NF_din_vld_dly;
  reg signed [21:0] Radix22ButterflyG2_NF_btf1_re_reg;  // sfix22
  reg signed [21:0] Radix22ButterflyG2_NF_btf1_im_reg;  // sfix22
  reg signed [21:0] Radix22ButterflyG2_NF_btf2_re_reg;  // sfix22
  reg signed [21:0] Radix22ButterflyG2_NF_btf2_im_reg;  // sfix22
  reg  Radix22ButterflyG2_NF_din_vld_dly_next;
  reg signed [21:0] Radix22ButterflyG2_NF_btf1_re_reg_next;  // sfix22
  reg signed [21:0] Radix22ButterflyG2_NF_btf1_im_reg_next;  // sfix22
  reg signed [21:0] Radix22ButterflyG2_NF_btf2_re_reg_next;  // sfix22
  reg signed [21:0] Radix22ButterflyG2_NF_btf2_im_reg_next;  // sfix22
  reg signed [20:0] dout_5_re_2;  // sfix21
  reg signed [20:0] dout_5_im_2;  // sfix21
  reg signed [20:0] dout_6_re_1;  // sfix21
  reg signed [20:0] dout_6_im_1;  // sfix21
  reg  dout_4_vld;
  reg signed [21:0] Radix22ButterflyG2_NF_t_0_0;  // sfix22
  reg signed [21:0] Radix22ButterflyG2_NF_t_1;  // sfix22
  reg signed [21:0] Radix22ButterflyG2_NF_t_2_0;  // sfix22
  reg signed [21:0] Radix22ButterflyG2_NF_t_3;  // sfix22
  reg signed [21:0] Radix22ButterflyG2_NF_t_4_0;  // sfix22
  reg signed [21:0] Radix22ButterflyG2_NF_t_5;  // sfix22
  reg signed [21:0] Radix22ButterflyG2_NF_t_6_0;  // sfix22
  reg signed [21:0] Radix22ButterflyG2_NF_t_7;  // sfix22
  reg signed [21:0] Radix22ButterflyG2_NF_t_8_0;  // sfix22
  reg signed [21:0] Radix22ButterflyG2_NF_t_9;  // sfix22
  reg signed [21:0] Radix22ButterflyG2_NF_t_10;  // sfix22
  reg signed [21:0] Radix22ButterflyG2_NF_t_11;  // sfix22
  reg signed [21:0] Radix22ButterflyG2_NF_t_12;  // sfix22
  reg signed [21:0] Radix22ButterflyG2_NF_t_13;  // sfix22
  reg signed [21:0] Radix22ButterflyG2_NF_t_14;  // sfix22
  reg signed [21:0] Radix22ButterflyG2_NF_t_15;  // sfix22


  assign din1_re = {dout_5_re[19], dout_5_re};



  assign din1_im = {dout_5_im[19], dout_5_im};



  assign din2_re = {dout_7_re[19], dout_7_re};



  assign din2_im = {dout_7_im[19], dout_7_im};



  // Radix22ButterflyG2_NF
  always @(posedge clk or posedge reset)
    begin : Radix22ButterflyG2_NF_process
      if (reset == 1'b1) begin
        Radix22ButterflyG2_NF_din_vld_dly <= 1'b0;
        Radix22ButterflyG2_NF_btf1_re_reg <= 22'sb0000000000000000000000;
        Radix22ButterflyG2_NF_btf1_im_reg <= 22'sb0000000000000000000000;
        Radix22ButterflyG2_NF_btf2_re_reg <= 22'sb0000000000000000000000;
        Radix22ButterflyG2_NF_btf2_im_reg <= 22'sb0000000000000000000000;
      end
      else begin
        if (enb_1_8_0) begin
          Radix22ButterflyG2_NF_din_vld_dly <= Radix22ButterflyG2_NF_din_vld_dly_next;
          Radix22ButterflyG2_NF_btf1_re_reg <= Radix22ButterflyG2_NF_btf1_re_reg_next;
          Radix22ButterflyG2_NF_btf1_im_reg <= Radix22ButterflyG2_NF_btf1_im_reg_next;
          Radix22ButterflyG2_NF_btf2_re_reg <= Radix22ButterflyG2_NF_btf2_re_reg_next;
          Radix22ButterflyG2_NF_btf2_im_reg <= Radix22ButterflyG2_NF_btf2_im_reg_next;
        end
      end
    end

  always @(Radix22ButterflyG2_NF_btf1_im_reg, Radix22ButterflyG2_NF_btf1_re_reg,
       Radix22ButterflyG2_NF_btf2_im_reg, Radix22ButterflyG2_NF_btf2_re_reg,
       Radix22ButterflyG2_NF_din_vld_dly, din1_im, din1_re, din2_im, din2_re,
       dout_1_vld, rotate_5) begin
    Radix22ButterflyG2_NF_t_0_0 = 22'sb0000000000000000000000;
    Radix22ButterflyG2_NF_t_1 = 22'sb0000000000000000000000;
    Radix22ButterflyG2_NF_t_2_0 = 22'sb0000000000000000000000;
    Radix22ButterflyG2_NF_t_3 = 22'sb0000000000000000000000;
    Radix22ButterflyG2_NF_t_4_0 = 22'sb0000000000000000000000;
    Radix22ButterflyG2_NF_t_5 = 22'sb0000000000000000000000;
    Radix22ButterflyG2_NF_t_6_0 = 22'sb0000000000000000000000;
    Radix22ButterflyG2_NF_t_7 = 22'sb0000000000000000000000;
    Radix22ButterflyG2_NF_t_8_0 = 22'sb0000000000000000000000;
    Radix22ButterflyG2_NF_t_9 = 22'sb0000000000000000000000;
    Radix22ButterflyG2_NF_t_10 = 22'sb0000000000000000000000;
    Radix22ButterflyG2_NF_t_11 = 22'sb0000000000000000000000;
    Radix22ButterflyG2_NF_t_12 = 22'sb0000000000000000000000;
    Radix22ButterflyG2_NF_t_13 = 22'sb0000000000000000000000;
    Radix22ButterflyG2_NF_t_14 = 22'sb0000000000000000000000;
    Radix22ButterflyG2_NF_t_15 = 22'sb0000000000000000000000;
    Radix22ButterflyG2_NF_btf1_re_reg_next = Radix22ButterflyG2_NF_btf1_re_reg;
    Radix22ButterflyG2_NF_btf1_im_reg_next = Radix22ButterflyG2_NF_btf1_im_reg;
    Radix22ButterflyG2_NF_btf2_re_reg_next = Radix22ButterflyG2_NF_btf2_re_reg;
    Radix22ButterflyG2_NF_btf2_im_reg_next = Radix22ButterflyG2_NF_btf2_im_reg;
    Radix22ButterflyG2_NF_din_vld_dly_next = dout_1_vld;
    if (rotate_5 != 1'b0) begin
      if (dout_1_vld) begin
        Radix22ButterflyG2_NF_t_0_0 = {din1_re[20], din1_re};
        Radix22ButterflyG2_NF_t_1 = {din2_im[20], din2_im};
        Radix22ButterflyG2_NF_btf1_re_reg_next = Radix22ButterflyG2_NF_t_0_0 + Radix22ButterflyG2_NF_t_1;
        Radix22ButterflyG2_NF_t_2_0 = {din1_re[20], din1_re};
        Radix22ButterflyG2_NF_t_3 = {din2_im[20], din2_im};
        Radix22ButterflyG2_NF_btf2_re_reg_next = Radix22ButterflyG2_NF_t_2_0 - Radix22ButterflyG2_NF_t_3;
        Radix22ButterflyG2_NF_t_4_0 = {din1_im[20], din1_im};
        Radix22ButterflyG2_NF_t_5 = {din2_re[20], din2_re};
        Radix22ButterflyG2_NF_btf2_im_reg_next = Radix22ButterflyG2_NF_t_4_0 + Radix22ButterflyG2_NF_t_5;
        Radix22ButterflyG2_NF_t_6_0 = {din1_im[20], din1_im};
        Radix22ButterflyG2_NF_t_7 = {din2_re[20], din2_re};
        Radix22ButterflyG2_NF_btf1_im_reg_next = Radix22ButterflyG2_NF_t_6_0 - Radix22ButterflyG2_NF_t_7;
      end
    end
    else if (dout_1_vld) begin
      Radix22ButterflyG2_NF_t_8_0 = {din1_re[20], din1_re};
      Radix22ButterflyG2_NF_t_9 = {din2_re[20], din2_re};
      Radix22ButterflyG2_NF_btf1_re_reg_next = Radix22ButterflyG2_NF_t_8_0 + Radix22ButterflyG2_NF_t_9;
      Radix22ButterflyG2_NF_t_10 = {din1_re[20], din1_re};
      Radix22ButterflyG2_NF_t_11 = {din2_re[20], din2_re};
      Radix22ButterflyG2_NF_btf2_re_reg_next = Radix22ButterflyG2_NF_t_10 - Radix22ButterflyG2_NF_t_11;
      Radix22ButterflyG2_NF_t_12 = {din1_im[20], din1_im};
      Radix22ButterflyG2_NF_t_13 = {din2_im[20], din2_im};
      Radix22ButterflyG2_NF_btf1_im_reg_next = Radix22ButterflyG2_NF_t_12 + Radix22ButterflyG2_NF_t_13;
      Radix22ButterflyG2_NF_t_14 = {din1_im[20], din1_im};
      Radix22ButterflyG2_NF_t_15 = {din2_im[20], din2_im};
      Radix22ButterflyG2_NF_btf2_im_reg_next = Radix22ButterflyG2_NF_t_14 - Radix22ButterflyG2_NF_t_15;
    end
    dout_5_re_2 = Radix22ButterflyG2_NF_btf1_re_reg[20:0];
    dout_5_im_2 = Radix22ButterflyG2_NF_btf1_im_reg[20:0];
    dout_6_re_1 = Radix22ButterflyG2_NF_btf2_re_reg[20:0];
    dout_6_im_1 = Radix22ButterflyG2_NF_btf2_im_reg[20:0];
    dout_4_vld = Radix22ButterflyG2_NF_din_vld_dly;
  end



  assign dout_5_re_1 = dout_5_re_2;

  assign dout_5_im_1 = dout_5_im_2;

  assign dout_6_re = dout_6_re_1;

  assign dout_6_im = dout_6_im_1;

endmodule  // RADIX22FFT_SDNF2_4_block1

