// -------------------------------------------------------------
// 
// File Name: C:\Users\jwbie\OneDrive\Documents\Academics\F22\551\551_Final_Project\fft_v2\hdl\joe_fft\RADIX22FFT_SDNF2_2.v
// Created: 2022-12-08 20:30:07
// 
// Generated by MATLAB 9.13 and HDL Coder 4.0
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: RADIX22FFT_SDNF2_2
// Source Path: joe_fft/FFT/RADIX22FFT_SDNF2_2
// Hierarchy Level: 2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module RADIX22FFT_SDNF2_2
          (clk,
           reset,
           enb_1_8_0,
           rotate_8,
           dout_1_1_re,
           dout_1_1_im,
           dout_1_5_re,
           dout_1_5_im,
           dout_1_1_vld,
           dout_1_re,
           dout_1_im,
           dout_2_re,
           dout_2_im,
           dout_2_vld);


  input   clk;
  input   reset;
  input   enb_1_8_0;
  input   rotate_8;  // ufix1
  input   signed [17:0] dout_1_1_re;  // sfix18
  input   signed [17:0] dout_1_1_im;  // sfix18
  input   signed [17:0] dout_1_5_re;  // sfix18
  input   signed [17:0] dout_1_5_im;  // sfix18
  input   dout_1_1_vld;
  output  signed [18:0] dout_1_re;  // sfix19
  output  signed [18:0] dout_1_im;  // sfix19
  output  signed [18:0] dout_2_re;  // sfix19
  output  signed [18:0] dout_2_im;  // sfix19
  output  dout_2_vld;


  wire signed [18:0] din1_re;  // sfix19
  wire signed [18:0] din1_im;  // sfix19
  wire signed [18:0] din2_re;  // sfix19
  wire signed [18:0] din2_im;  // sfix19
  reg  Radix22ButterflyG2_NF_din_vld_dly;
  reg signed [19:0] Radix22ButterflyG2_NF_btf1_re_reg;  // sfix20
  reg signed [19:0] Radix22ButterflyG2_NF_btf1_im_reg;  // sfix20
  reg signed [19:0] Radix22ButterflyG2_NF_btf2_re_reg;  // sfix20
  reg signed [19:0] Radix22ButterflyG2_NF_btf2_im_reg;  // sfix20
  reg  Radix22ButterflyG2_NF_din_vld_dly_next;
  reg signed [19:0] Radix22ButterflyG2_NF_btf1_re_reg_next;  // sfix20
  reg signed [19:0] Radix22ButterflyG2_NF_btf1_im_reg_next;  // sfix20
  reg signed [19:0] Radix22ButterflyG2_NF_btf2_re_reg_next;  // sfix20
  reg signed [19:0] Radix22ButterflyG2_NF_btf2_im_reg_next;  // sfix20
  reg signed [18:0] dout_1_re_1;  // sfix19
  reg signed [18:0] dout_1_im_1;  // sfix19
  reg signed [18:0] dout_2_re_1;  // sfix19
  reg signed [18:0] dout_2_im_1;  // sfix19
  reg  dout_2_vld_1;
  reg signed [19:0] Radix22ButterflyG2_NF_t_0_0;  // sfix20
  reg signed [19:0] Radix22ButterflyG2_NF_t_1;  // sfix20
  reg signed [19:0] Radix22ButterflyG2_NF_t_2_0;  // sfix20
  reg signed [19:0] Radix22ButterflyG2_NF_t_3;  // sfix20
  reg signed [19:0] Radix22ButterflyG2_NF_t_4_0;  // sfix20
  reg signed [19:0] Radix22ButterflyG2_NF_t_5;  // sfix20
  reg signed [19:0] Radix22ButterflyG2_NF_t_6_0;  // sfix20
  reg signed [19:0] Radix22ButterflyG2_NF_t_7;  // sfix20
  reg signed [19:0] Radix22ButterflyG2_NF_t_8_0;  // sfix20
  reg signed [19:0] Radix22ButterflyG2_NF_t_9;  // sfix20
  reg signed [19:0] Radix22ButterflyG2_NF_t_10;  // sfix20
  reg signed [19:0] Radix22ButterflyG2_NF_t_11;  // sfix20
  reg signed [19:0] Radix22ButterflyG2_NF_t_12;  // sfix20
  reg signed [19:0] Radix22ButterflyG2_NF_t_13;  // sfix20
  reg signed [19:0] Radix22ButterflyG2_NF_t_14;  // sfix20
  reg signed [19:0] Radix22ButterflyG2_NF_t_15;  // sfix20


  assign din1_re = {dout_1_1_re[17], dout_1_1_re};



  assign din1_im = {dout_1_1_im[17], dout_1_1_im};



  assign din2_re = {dout_1_5_re[17], dout_1_5_re};



  assign din2_im = {dout_1_5_im[17], dout_1_5_im};



  // Radix22ButterflyG2_NF
  always @(posedge clk or posedge reset)
    begin : Radix22ButterflyG2_NF_process
      if (reset == 1'b1) begin
        Radix22ButterflyG2_NF_din_vld_dly <= 1'b0;
        Radix22ButterflyG2_NF_btf1_re_reg <= 20'sb00000000000000000000;
        Radix22ButterflyG2_NF_btf1_im_reg <= 20'sb00000000000000000000;
        Radix22ButterflyG2_NF_btf2_re_reg <= 20'sb00000000000000000000;
        Radix22ButterflyG2_NF_btf2_im_reg <= 20'sb00000000000000000000;
      end
      else begin
        if (enb_1_8_0) begin
          Radix22ButterflyG2_NF_din_vld_dly <= Radix22ButterflyG2_NF_din_vld_dly_next;
          Radix22ButterflyG2_NF_btf1_re_reg <= Radix22ButterflyG2_NF_btf1_re_reg_next;
          Radix22ButterflyG2_NF_btf1_im_reg <= Radix22ButterflyG2_NF_btf1_im_reg_next;
          Radix22ButterflyG2_NF_btf2_re_reg <= Radix22ButterflyG2_NF_btf2_re_reg_next;
          Radix22ButterflyG2_NF_btf2_im_reg <= Radix22ButterflyG2_NF_btf2_im_reg_next;
        end
      end
    end

  always @(Radix22ButterflyG2_NF_btf1_im_reg, Radix22ButterflyG2_NF_btf1_re_reg,
       Radix22ButterflyG2_NF_btf2_im_reg, Radix22ButterflyG2_NF_btf2_re_reg,
       Radix22ButterflyG2_NF_din_vld_dly, din1_im, din1_re, din2_im, din2_re,
       dout_1_1_vld, rotate_8) begin
    Radix22ButterflyG2_NF_t_0_0 = 20'sb00000000000000000000;
    Radix22ButterflyG2_NF_t_1 = 20'sb00000000000000000000;
    Radix22ButterflyG2_NF_t_2_0 = 20'sb00000000000000000000;
    Radix22ButterflyG2_NF_t_3 = 20'sb00000000000000000000;
    Radix22ButterflyG2_NF_t_4_0 = 20'sb00000000000000000000;
    Radix22ButterflyG2_NF_t_5 = 20'sb00000000000000000000;
    Radix22ButterflyG2_NF_t_6_0 = 20'sb00000000000000000000;
    Radix22ButterflyG2_NF_t_7 = 20'sb00000000000000000000;
    Radix22ButterflyG2_NF_t_8_0 = 20'sb00000000000000000000;
    Radix22ButterflyG2_NF_t_9 = 20'sb00000000000000000000;
    Radix22ButterflyG2_NF_t_10 = 20'sb00000000000000000000;
    Radix22ButterflyG2_NF_t_11 = 20'sb00000000000000000000;
    Radix22ButterflyG2_NF_t_12 = 20'sb00000000000000000000;
    Radix22ButterflyG2_NF_t_13 = 20'sb00000000000000000000;
    Radix22ButterflyG2_NF_t_14 = 20'sb00000000000000000000;
    Radix22ButterflyG2_NF_t_15 = 20'sb00000000000000000000;
    Radix22ButterflyG2_NF_btf1_re_reg_next = Radix22ButterflyG2_NF_btf1_re_reg;
    Radix22ButterflyG2_NF_btf1_im_reg_next = Radix22ButterflyG2_NF_btf1_im_reg;
    Radix22ButterflyG2_NF_btf2_re_reg_next = Radix22ButterflyG2_NF_btf2_re_reg;
    Radix22ButterflyG2_NF_btf2_im_reg_next = Radix22ButterflyG2_NF_btf2_im_reg;
    Radix22ButterflyG2_NF_din_vld_dly_next = dout_1_1_vld;
    if (rotate_8 != 1'b0) begin
      if (dout_1_1_vld) begin
        Radix22ButterflyG2_NF_t_0_0 = {din1_re[18], din1_re};
        Radix22ButterflyG2_NF_t_1 = {din2_im[18], din2_im};
        Radix22ButterflyG2_NF_btf1_re_reg_next = Radix22ButterflyG2_NF_t_0_0 + Radix22ButterflyG2_NF_t_1;
        Radix22ButterflyG2_NF_t_2_0 = {din1_re[18], din1_re};
        Radix22ButterflyG2_NF_t_3 = {din2_im[18], din2_im};
        Radix22ButterflyG2_NF_btf2_re_reg_next = Radix22ButterflyG2_NF_t_2_0 - Radix22ButterflyG2_NF_t_3;
        Radix22ButterflyG2_NF_t_4_0 = {din1_im[18], din1_im};
        Radix22ButterflyG2_NF_t_5 = {din2_re[18], din2_re};
        Radix22ButterflyG2_NF_btf2_im_reg_next = Radix22ButterflyG2_NF_t_4_0 + Radix22ButterflyG2_NF_t_5;
        Radix22ButterflyG2_NF_t_6_0 = {din1_im[18], din1_im};
        Radix22ButterflyG2_NF_t_7 = {din2_re[18], din2_re};
        Radix22ButterflyG2_NF_btf1_im_reg_next = Radix22ButterflyG2_NF_t_6_0 - Radix22ButterflyG2_NF_t_7;
      end
    end
    else if (dout_1_1_vld) begin
      Radix22ButterflyG2_NF_t_8_0 = {din1_re[18], din1_re};
      Radix22ButterflyG2_NF_t_9 = {din2_re[18], din2_re};
      Radix22ButterflyG2_NF_btf1_re_reg_next = Radix22ButterflyG2_NF_t_8_0 + Radix22ButterflyG2_NF_t_9;
      Radix22ButterflyG2_NF_t_10 = {din1_re[18], din1_re};
      Radix22ButterflyG2_NF_t_11 = {din2_re[18], din2_re};
      Radix22ButterflyG2_NF_btf2_re_reg_next = Radix22ButterflyG2_NF_t_10 - Radix22ButterflyG2_NF_t_11;
      Radix22ButterflyG2_NF_t_12 = {din1_im[18], din1_im};
      Radix22ButterflyG2_NF_t_13 = {din2_im[18], din2_im};
      Radix22ButterflyG2_NF_btf1_im_reg_next = Radix22ButterflyG2_NF_t_12 + Radix22ButterflyG2_NF_t_13;
      Radix22ButterflyG2_NF_t_14 = {din1_im[18], din1_im};
      Radix22ButterflyG2_NF_t_15 = {din2_im[18], din2_im};
      Radix22ButterflyG2_NF_btf2_im_reg_next = Radix22ButterflyG2_NF_t_14 - Radix22ButterflyG2_NF_t_15;
    end
    dout_1_re_1 = Radix22ButterflyG2_NF_btf1_re_reg[18:0];
    dout_1_im_1 = Radix22ButterflyG2_NF_btf1_im_reg[18:0];
    dout_2_re_1 = Radix22ButterflyG2_NF_btf2_re_reg[18:0];
    dout_2_im_1 = Radix22ButterflyG2_NF_btf2_im_reg[18:0];
    dout_2_vld_1 = Radix22ButterflyG2_NF_din_vld_dly;
  end



  assign dout_1_re = dout_1_re_1;

  assign dout_1_im = dout_1_im_1;

  assign dout_2_re = dout_2_re_1;

  assign dout_2_im = dout_2_im_1;

  assign dout_2_vld = dout_2_vld_1;

endmodule  // RADIX22FFT_SDNF2_2

